### ISSUE TITLE
Error when itsa.model called

### ISSUE THREAD

**Issue by abrajeffers** [patrick-eng/its.analysis#2]
I am trying to run an itsa.model but I get the following error after I call the function on either my real data or my example data below:
_Error in order(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), c(1L, 1L, 1L,  : 
  unimplemented type 'list' in 'listgreater'
In addition: Warning messages:
1: In cbind(x, time) :
  number of rows of result is not a multiple of vector length (arg 1)
2: In min(temp$depvar) : no non-missing arguments to min; returning Inf
3: In max(temp$depvar) : no non-missing arguments to max; returning -Inf_

Example code:
```
r_1 = c(-23,-27,-5,-14,-21,4,-2,-6,-6,0)
cov1 = c(0.6,-0.3,0.1,-0.2,-0.8,-0.4,-0.5,-0.2,-0.1,-1.5)
cov2 = c(0,0,0.5,-0.4,-0.1,-1.2,0.8,-0.9,0,0)
time = 1:10
intn = ts(c(rep(0,4),rep(1,6)),start = 1, end = 10)
ts_r = ts.union(r_1,cov1,cov2,time,intn)
model.ym <- itsa.model(data = ts_r,time = "time",depvar = "r_1",interrupt_var = "intn",
covariates = c("cov1","cov2"),bootstrap = FALSE)
```
Any idea of what's going on?

**Comment by patrick-eng** [comment]
Firstly, my apologies that it has taken me so long to get back to you here! I have no idea where my GitHub notification emails are supposed to be going, but clearly it isn't anywhere I am seeing them.

Secondly, the issue is seemingly solved by adding a pipe on line eight and converting the object ts_r into a data frame:

`ts_r = ts.union(r_1,cov1,cov2,time,intn) %>% 
  as.data.frame()` 

The way I have coded the package means that it uses a combination of indexing and element extraction to move vectors around, so the safest way to do that (at least, according to past me) was by using data frames.

Thanks for raising this issue! On the next update I will either find a way for it to accept mts/ts/matrix class, or (more likely) add a data frame coercion to the top of the code. 

Let me know if you have any further problems!
